---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/flannel-io/flannel/v0.24.0/Documentation/kustomization/kube-flannel/kube-flannel.yml
patches:
- path: configmap.yaml
  target:
    kind: ConfigMap